"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ADULT_AGE_THRESHOLD = exports.CORS_HEADERS = exports.AGE_BANDS = exports.STORY_LENGTHS = exports.STORY_POVS = exports.STORY_TONES = exports.ALL_GENRES = void 0;
var constants_1 = require("lambda_shared/constants");
Object.defineProperty(exports, "ALL_GENRES", { enumerable: true, get: function () { return constants_1.ALL_GENRES; } });
Object.defineProperty(exports, "STORY_TONES", { enumerable: true, get: function () { return constants_1.STORY_TONES; } });
Object.defineProperty(exports, "STORY_POVS", { enumerable: true, get: function () { return constants_1.STORY_POVS; } });
Object.defineProperty(exports, "STORY_LENGTHS", { enumerable: true, get: function () { return constants_1.STORY_LENGTHS; } });
Object.defineProperty(exports, "AGE_BANDS", { enumerable: true, get: function () { return constants_1.AGE_BANDS; } });
Object.defineProperty(exports, "CORS_HEADERS", { enumerable: true, get: function () { return constants_1.CORS_HEADERS; } });
Object.defineProperty(exports, "ADULT_AGE_THRESHOLD", { enumerable: true, get: function () { return constants_1.ADULT_AGE_THRESHOLD; } });
