export {
  VALID_GENRES as ADULT_GENRES,
  VALID_CHILD_GENRES as CHILD_GENRES,
  VALID_CHILD_AGE_BANDS as CHILD_AGE_BANDS,
  VALID_GRL_VALUES as READING_LEVELS_GRL,
  VALID_LANGUAGES as LANGUAGES,
  DEFAULT_LANGUAGE,
  CORS_HEADERS,
  ADULT_AGE_THRESHOLD,
} from 'lambda_shared/constants';

export const MAX_CHILD_PROFILES = 5;

